// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://example.com/terms/",
        "contact": {
            "name": "API Support",
            "email": "karolmalicki.001@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add-user": {
            "post": {
                "description": "Redirects the user to Google OAuth2 authorization page to allow app access.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Initiates user authorization",
                "responses": {
                    "200": {
                        "description": "User authorization link",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error initiating authorization",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/add-user-to-group": {
            "post": {
                "description": "Adds a specified user to a specified group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Add a user to a group",
                "parameters": [
                    {
                        "description": "User Email",
                        "name": "user_email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Group Name",
                        "name": "group_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User added to group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error adding user to group",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/check-availability": {
            "get": {
                "description": "Retrieves free slots from the user's Google Calendar within a given time range.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "Check user calendar availability",
                "responses": {
                    "200": {
                        "description": "List of free slots",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error retrieving availability",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list-groups": {
            "get": {
                "description": "Retrieves the list of all groups from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "List all groups",
                "responses": {
                    "200": {
                        "description": "List of groups",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error listing groups",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list-users": {
            "get": {
                "description": "Retrieves the list of all users from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error listing users",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth2callback": {
            "get": {
                "description": "Handles the Google OAuth2 callback and stores the access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Handles OAuth2 callback",
                "responses": {
                    "200": {
                        "description": "Authorization successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error during OAuth2 callback",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/routes": {
            "get": {
                "description": "Defines all the routes and the associated handlers for the application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Routes"
                ],
                "summary": "Set up API routes for the application",
                "responses": {
                    "200": {
                        "description": "Routes set successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Calendar Meeting Scheduler API",
	Description:      "API for scheduling meetings and managing users/groups using Google Calendar.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
